<?php
/**
 * Created by PhpStorm.
 * User: EricPan
 * Date: 2019/5/29
 * Time: 14:57
 */

namespace App\Admin\Extensions;

use App\Models\User;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Grid\Exporters\ExcelExporter;
use Maatwebsite\Excel\Facades\Excel;

class UsersExport extends ExcelExporter
{
    protected $fileName = '渠道商导出.xlsx';

    protected $headings = ['ID','姓名','电话','外拓经理','类型','备注','银行','卡号','创建时间'];

    public function export()
    {
//        parent::export(); // TODO: Change the autogenerated stub
        $isCaiwu = Admin::user()->isRole('caiwu');
        $isPutong= Admin::user()->isRole('putong');
        $isAdmin= Admin::user()->isRole('administrator');
        $rows = [];
        $rows[] = $this->headings;

        $data = $this->getData();

        if(count($data))
        {
            foreach ($data as $v)
            {
                $row = [];
                $row[] = $v['id'];
                $row[] = $v['name'];
                $row[] = $isAdmin?$v['phone']:substr($v['phone'],0,9).'**';
                $row[] = $v['top']['name'];
                $row[] = User::$type[$v['type']];
                $row[] = $v['remark'];
                $row[] = $v['bank_name'];
                $row[] = $v['card_number'];
                $row[] = $v['created_at'];
                $rows[] = $row;
            }
        }

        // 数据格式化
        $export = new InvoicesExport($rows);

        // 导出
        return Excel::download($export, $this->fileName)->send();
    }
}
